name: Execução dos testes de front-end 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd projeto-de-testes
        npm install
        ./node_modules/.bin/cypress run --spec 'cypress/e2e/**/'
    - name: Install Allure Command Line
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure
    - name: Generate Allure Report
      run: |
        allure generate ./cypress/reports/allure-results --clean -o ./cypress/reports/allure-report
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./cypress/reports/allure-report
