name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd projeto-de-testes
        npm install
        ./node_modules/.bin/cypress run --spec 'cypress/e2e/**/'
  
    - name: Generate report 
      run: cd projeto-de-testes && npm run postcypress:run
    
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: cypress-cucumber-report
        path: projeto-de-testes/cypress/reports

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./cypress/reports
